spring.application.name=Neotrack-Backend

# PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/NeoTrack}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Est#4444}
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=${PORT:8081}
server.address=0.0.0.0


# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=${JWT_SECRET:neotrack-super-secret-key-for-jwt-signing-2024}
jwt.expiration=86400000
